// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfpxezisVdDOBHpEC2-b7BXfzhiiNfcsM',
    appId: '1:746091179193:android:edce7f146cbfde4509ff68',
    messagingSenderId: '746091179193',
    projectId: 'lugat-b17bf',
    storageBucket: 'lugat-b17bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcEaIb09Zc_ssGooMFb0VDZr46S6Dff4I',
    appId: '1:746091179193:ios:8fa7146d6042c30a09ff68',
    messagingSenderId: '746091179193',
    projectId: 'lugat-b17bf',
    storageBucket: 'lugat-b17bf.appspot.com',
    androidClientId: '746091179193-3c5ersbluppii2ddmv9rj5stfpau4bsp.apps.googleusercontent.com',
    iosClientId: '746091179193-grm021qkidiej4ktn5sphgfk4s8pb67e.apps.googleusercontent.com',
    iosBundleId: 'com.example.lugat',
  );
}
